title: Kai Cooper
url: "https://kai-coo-per.github.io"  # user/org site root
baseurl: ""                           # IMPORTANT: empty for user sites

plugins:
  - jekyll-remote-theme               # GitHub Pages allows this

remote_theme: ankitsultana/researcher # The Researcher theme

# (optional theme settings)
# ins_logo: "./bits-logo.png"
# tracking_id:
footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "KC_CV_2025.pdf"
 - name: "Contact"
   link: "contact"

defaults:
  - scope: { path: "", type: news }
    values: { layout: news }

collections:
  news:
    output: true
    permalink: /news/:slug/

